<a href="https://colab.research.google.com/github/1vanAndreev/Python_Course/blob/main/lab9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Первое задание


In [36]:
import numpy as np

In [37]:
matrix = np.eye(12)

In [38]:
matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Второе задание


In [51]:
import numpy as np

In [64]:
matrix = np.ones((9, 9), dtype=int)

In [65]:
matrix[::2, ::2] = 0

In [66]:
matrix[1::2, 1::2] = 0

In [67]:
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0]])

# Третье задание


In [56]:
import numpy as np

In [77]:
np.random.seed(42)
vector = np.random.random(10)
vector

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [78]:
vector.sort()

In [79]:
vector

array([0.05808361, 0.15599452, 0.15601864, 0.37454012, 0.59865848,
       0.60111501, 0.70807258, 0.73199394, 0.86617615, 0.95071431])

# Четвертое задание


In [99]:
np.random.seed(42)
fourth_array = np.random.randint(3, 5,(8, 3))
fourth_array

array([[3, 4, 3],
       [3, 3, 4],
       [3, 3, 3],
       [4, 3, 3],
       [3, 3, 4],
       [3, 4, 4],
       [4, 3, 4],
       [3, 4, 4]])

In [88]:
result = np.all(fourth_array == 4, axis=1)

In [90]:
np.any(result)

False

# Пятое задание

In [92]:
import numpy as np

In [91]:
array = np.zeros(6)

In [93]:
array[-1] = 1

In [95]:
array

array([0., 0., 0., 0., 0., 1.])

# Шестое задание

In [101]:
import numpy as np

In [105]:
np.unravel_index(9, (2,3,2))

(1, 1, 1)